github: fix tests by switching to buster images for old perls
See https://github.com/Perl/docker-perl/issues/161 for more information.

Otherwise we get:

    /usr/bin/docker pull perl:5.20
      5.20: Pulling from library/perl
      [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/perl:5.20 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
      Warning: Docker pull failed with exit code 1, back off 7.724 seconds before retry.
      /usr/bin/docker pull perl:5.20
      5.20: Pulling from library/perl
      [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/perl:5.20 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
      Warning: Docker pull failed with exit code 1, back off 9.064 seconds before retry.
      /usr/bin/docker pull perl:5.20
      5.20: Pulling from library/perl
      [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/perl:5.20 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
      Error: Docker pull failed with exit code 1